services:
  - mysql
before_install:
  - mysql -e 'create database mashtru;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - composer install --prefer-dist --no-interaction

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
script:
  - vendor/bin/phpunit

notifications:
  email: false
